spring.application.name=publish-ride-service
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#spring.datasource.url=jdbc:mysql://localhost:3306/ride_service
#spring.datasource.username=root
#spring.datasource.password=admin
server.port=8082
#spring.jpa.hibernate.ddl.auto=none
spring.jpa.show-sql=true
app.ride-service-pending-rides-endpoint=http://localhost:8081/api/ride/getRidesByStatus?status={status}
app.ride-service-update-rides-status-endpoint=http://localhost:8081/api/ride/updateRidesStatus


##KAFKA SETUP
# Bootstrap servers
spring.kafka.bootstrap-servers=localhost:9092

# com.test.Producer: serialize keys as strings and values as JSON
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# com.test.Consumer: deserialize keys as strings and values as JSON
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# JSON Deserializer: specify the class of the object being consumed
#spring.kafka.consumer.properties.spring.json.value.default.type=com.example.demo.User
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.group-id=my-group