spring.application.name=ride-dispatch-service
app.driver-service-get-pending-services-endpoint =http://localhost:8082/api/publish-ride/getAllPendingRides
app.driver-service.get-all-active-drivers-endpoint =http://localhost:8082/api/publish-ride/getAllUsersByUserTypeAndStatus


##KAFKA SETUP
# Bootstrap servers
spring.kafka.bootstrap-servers=localhost:9092

# com.test.Producer: serialize keys as strings and values as JSON
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# com.test.Consumer: deserialize keys as strings and values as JSON
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# JSON Deserializer: specify the class of the object being consumed
#spring.kafka.consumer.properties.spring.json.value.default.type=com.example.demo.User
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.group-id=my-group