spring.application.name=driver-service
app.driver-service-get-pending-services-endpoint =http://localhost:8082/api/publish-ride/getAllPendingRides
app.driver-service.get-all-active-drivers-endpoint =http://localhost:8082/api/publish-ride/getAllUsersByUserTypeAndStatus
